Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Users"
      AttributeDefinitions:
        - AttributeName: "username"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "username"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"